# default format of graph and axis titles (for plotExport.R)
defaultGGTitle:
  text: ""
  fontType: "plain"
  color: "#000000"
  size: 12
  hide: false

defaultBaseTitle:
  text: ""
  fontType: 1
  color: "#000000"
  size: 1.2
  hide: false

# default range of axis (for plotExport.R)
defaultRange:
  min: 0
  max: 1
  fromData: true
