# default format of graph and axis titles (for plotExport.R)
availableElements:
  title:
    plot title: "plotTitle"
  axis:
    x axis title: "xAxisTitle"
    x axis text: "xAxisText"
    y axis title: "yAxisTitle"
    y axis text: "yAxisText"
  legend:
    legend title: "legendTitle"
    legend text: "legendText"

defaultGGTitle:
  text: ""
  fontFamily: "sans"
  fontType: "plain"
  color: "#000000"
  size: 12
  hide: false

defaultBaseTitle:
  text: ""
  fontFamily: "sans"
  fontType: 1
  color: "#000000"
  size: 1.2
  hide: false

defaultGGText:
  fontFamily: "sans"
  fontType: "plain"
  color: "#000000"
  size: 10
  hide: false
  angle: 0
  hjust: 0.5
  vjust: 0.5

defaultBaseText:
  fontFamily: "sans"
  fontType: 1
  color: "#000000"
  size: 1
  hide: false
  angle: 0
  hjust: 0.5
  vjust: 0.5

# default range of axis (for plotExport.R)
defaultRange:
  min: 0
  max: 1
  fromData: true

# default point style
defaultPointStyle:
  dataPoints:
    symbol: 19
    color: "#000000"
    colorBg: "#000000"
    size: 1
    alpha: 1
    lineWidthBg: 2
    hide: false
