# default format of graph and axis titles (for plotExport.R)

defaultGGTitle:
  text: ""
  useExpression: false
  expression: ""
  fontFamily: "sans"
  fontType: "plain"
  color: "#000000"
  size: 12
  hide: false
  angle: 0
  hjust: 0.5
  vjust: 0.5

defaultBaseTitle:
  text: ""
  useExpression: false
  expression: ""
  fontFamily: "sans"
  fontType: 1
  color: "#000000"
  size: 1.2
  hide: false
  angle: 0
  hjust: 0.5
  vjust: 0.5

defaultGGText:
  text: ""
  useExpression: false
  expression: ""
  fontFamily: "sans"
  fontType: "plain"
  color: "#000000"
  size: 10
  hide: false
  angle: 0
  hjust: 0.5
  vjust: 0.5

defaultBaseText:
  text: ""
  useExpression: false
  expression: ""
  fontFamily: "sans"
  fontType: 1
  color: "#000000"
  size: 1
  hide: false
  angle: 0
  hjust: 0.5
  vjust: 0.5

# default range of axis (for plotExport.R)
defaultRange:
  min: 0
  max: 1
  fromData: true
  transform: "identity"

# default point style
defaultPointStyle:
  dataPoints:
    symbol: 19
    color: "#000000"
    colorBg: "#000000"
    size: 1
    alpha: 1
    lineWidthBg: 2
    hide: false

# default point style
defaultLineStyle:
  lineType: 1
  color: "#000000"
  size: 1
  alpha: 1
  lineWidth: 2
  hide: false
